package fr.arnaud_camus.leren

import android.app.Application
import fr.arnaud_camus.leren.models.Word

/**
 * Created by arnaud on 3/6/16.
 */
class LerenApplication: Application() {
    val mockData: Array<Word> = arrayOf(Word(english = "Goodbye", dutch = "Tot ziens", categoryName = "Basics"),
            Word(english = "Good morning", dutch = "Goedemorgen", categoryName = "Basics"),
            Word(english = "Good afternoon", dutch = "Goedemiddag", categoryName = "Basics"),
            Word(english = "Good evening", dutch = "Goedenavond", categoryName = "Basics"),
            Word(english = "Yes", dutch = "Ja", categoryName = "Basics"),
            Word(english = "No", dutch = "Nee", categoryName = "Basics"),
            Word(english = "Please", dutch = "Alsjeblieft", categoryName = "Basics"),
            Word(english = "Thanks", dutch = "Dankjewel", categoryName = "Basics"),
            Word(english = "My name is ..", dutch = "Ik heet ..", categoryName = "Basics"),
            Word(english = "What is your name?", dutch = "Hoe heet jij?", categoryName = "Basics"),
            Word(english = "How are you?", dutch = "Hoe gaat het met jou?", categoryName = "Basics"),
            Word(english = "Fine and you?", dutch = "Goed en met jou?", categoryName = "Basics"),
            Word(english = "Pleased to meet you", dutch = "Aangenaam kennis te maken", categoryName = "Basics"),
            Word(english = "See you later", dutch = "Tot ziens", categoryName = "Basics"),
            Word(english = "Sorry", dutch = "Sorry", categoryName = "Basics"),
            Word(english = "Excuse me", dutch = "Pardon", categoryName = "Basics"),
            Word(english = "Can you help me please?", dutch = "Kun je me helpen alsjeblieft?", categoryName = "Basics"),
            Word(english = "I am trying to learn Dutch", dutch = "Ik probeer Nederlands te leren", categoryName = "Basics"),
            Word(english = "Sunday", dutch = "zondag", categoryName = "Color"),
            Word(english = "It is red", dutch = "Het is rood", categoryName = "Color"),
            Word(english = "It is blue", dutch = "Het is blauw", categoryName = "Color"),
            Word(english = "black", dutch = "Zwart", categoryName = "Color"),
            Word(english = "blue", dutch = "Blauw", categoryName = "Color"),
            Word(english = "green", dutch = "Groen", categoryName = "Color"),
            Word(english = "orange", dutch = "Oranje", categoryName = "Color"),
            Word(english = "purple", dutch = "Paars", categoryName = "Color"),
            Word(english = "red", dutch = "Rood", categoryName = "Color"),
            Word(english = "yellow", dutch = "Geel", categoryName = "Color"),
            Word(english = "white", dutch = "Wit", categoryName = "Color"),
            Word(english = "This is my wife", dutch = "Dit is mijn vrouw", categoryName = "Family"),
            Word(english = "This is my husband", dutch = "Dit is mijn man", categoryName = "Family"),
            Word(english = "This is my son", dutch = "Dit is mijn zoon", categoryName = "Family"),
            Word(english = "This is my daughter", dutch = "Dit is mijn dochter", categoryName = "Family"),
            Word(english = "the father", dutch = "De vader", categoryName = "Family"),
            Word(english = "the mother", dutch = "De moeder", categoryName = "Family"),
            Word(english = "the husband", dutch = "De echtgenoot", categoryName = "Family"),
            Word(english = "the wife", dutch = "De echtgenote", categoryName = "Family"),
            Word(english = "the brother", dutch = "De broer", categoryName = "Family"),
            Word(english = "the sister", dutch = "De zus", categoryName = "Family"),
            Word(english = "the son", dutch = "De zoon", categoryName = "Family"),
            Word(english = "the daughter", dutch = "De dochter", categoryName = "Family"),
            Word(english = "the girlfriend", dutch = "De vriendin", categoryName = "Family"),
            Word(english = "the boyfriend", dutch = "De vriend", categoryName = "Family"),
            Word(english = "the coffee", dutch = "De koffie", categoryName = "Food"),
            Word(english = "the milk", dutch = "De melk", categoryName = "Food"),
            Word(english = "For the first course", dutch = "Als voorgerecht", categoryName = "Food"),
            Word(english = "For the second course", dutch = "Als hoofdgerecht", categoryName = "Food"),
            Word(english = "For dessert", dutch = "Als dessert", categoryName = "Food"),
            Word(english = "I don't eat meat", dutch = "Ik eet geen vlees", categoryName = "Food"),
            Word(english = "the salt", dutch = "het zout", categoryName = "Food"),
            Word(english = "the pepper", dutch = "de peper", categoryName = "Food"),
            Word(english = "the sugar", dutch = "de suiker", categoryName = "Food"),
            Word(english = "the vinegar", dutch = "de azijn", categoryName = "Food"),
            Word(english = "the sauce", dutch = "de saus", categoryName = "Food"),
            Word(english = "the mustard", dutch = "de moster", categoryName = "Food"),
            Word(english = "Is food available here?", dutch = "Heeft u iets te eten hier?", categoryName = "Food"),
            Word(english = "What sandwiches do you have?", dutch = "Wat voor broodjes heeft u?", categoryName = "Food"),
            Word(english = "A black coffee please", dutch = "Een zwarte koffie alstublieft", categoryName = "Food"),
            Word(english = "A white coffee please", dutch = "Een koffie met melk alstublieft", categoryName = "Food"),
            Word(english = "Two white coffees please", dutch = "Twee koffie met melk alstublieft", categoryName = "Food"),
            Word(english = "A tea with milk", dutch = "Een thee met melk", categoryName = "Food"),
            Word(english = "A lemon tea", dutch = "Een thee met citroen", categoryName = "Food"),
            Word(english = "A lemonade please", dutch = "Een limonade alstublieft", categoryName = "Food"),
            Word(english = "A beer please", dutch = "Een bier alstublieft", categoryName = "Food"),
            Word(english = "Two beers", dutch = "Twee bier", categoryName = "Food"),
            Word(english = "A glass of red wine", dutch = "Een glas rode wijn", categoryName = "Food"),
            Word(english = "A glass of white wine", dutch = "Een glas witte wijn", categoryName = "Food"),
            Word(english = "A bottle of house white wine", dutch = "Een fles witte huiswijn", categoryName = "Food"),
            Word(english = "A bottle of house red wine", dutch = "Een fles rode huiswijn", categoryName = "Food"),
            Word(english = "A gin and tonic please", dutch = "Een gin-tonic alstublieft", categoryName = "Food"),
            Word(english = "An orange juice please", dutch = "Een sinaasappelsap alstublieft", categoryName = "Food"),
            Word(english = "With ice", dutch = "Met ijs", categoryName = "Food"),
            Word(english = "A mineral water", dutch = "Een spa", categoryName = "Food"),
            Word(english = "sparkling", dutch = "Met prik", categoryName = "Food"),
            Word(english = "still", dutch = "Zonder prik", categoryName = "Food"),
            Word(english = "vodka", dutch = "Wodka", categoryName = "Food"),
            Word(english = "the bread", dutch = "het brood", categoryName = "Food"),
            Word(english = "the butter", dutch = "de boter", categoryName = "Food"),
            Word(english = "the cheese", dutch = "de kaas", categoryName = "Food"),
            Word(english = "the chips", dutch = "de friet", categoryName = "Food"),
            Word(english = "the egg", dutch = "het ei", categoryName = "Food"),
            Word(english = "the ice-cream", dutch = "het ijsje", categoryName = "Food"),
            Word(english = "an omelette", dutch = "de omelet", categoryName = "Food"),
            Word(english = "the rice", dutch = "de rijst", categoryName = "Food"),
            Word(english = "the salad", dutch = "de salade", categoryName = "Food"),
            Word(english = "the soup", dutch = "de soep", categoryName = "Food"),
            Word(english = "the apple", dutch = "de appel", categoryName = "Food"),
            Word(english = "the banana", dutch = "de banaan", categoryName = "Food"),
            Word(english = "the cherry", dutch = "de kers", categoryName = "Food"),
            Word(english = "the grape", dutch = "de druif", categoryName = "Food"),
            Word(english = "the lemon", dutch = "de citroen", categoryName = "Food"),
            Word(english = "the melon", dutch = "de meloen", categoryName = "Food"),
            Word(english = "the orange", dutch = "de sinaasappel", categoryName = "Food"),
            Word(english = "the peach", dutch = "de perzik", categoryName = "Food"),
            Word(english = "the pear", dutch = "de peer", categoryName = "Food"),
            Word(english = "the pineapple", dutch = "de ananas", categoryName = "Food"),
            Word(english = "the carrot", dutch = "de wortel", categoryName = "Food"),
            Word(english = "the cucumber", dutch = "de komkommer", categoryName = "Food"),
            Word(english = "the garlic", dutch = "het knoflook", categoryName = "Food"),
            Word(english = "the lettuce", dutch = "de sla", categoryName = "Food"),
            Word(english = "the mushroom", dutch = "de champignon", categoryName = "Food"),
            Word(english = "the pea", dutch = "de erwt", categoryName = "Food"),
            Word(english = "the onion", dutch = "de ui", categoryName = "Food"),
            Word(english = "the potato", dutch = "de aardappel", categoryName = "Food"),
            Word(english = "the tomato", dutch = "de tomaat", categoryName = "Food"),
            Word(english = "the bacon", dutch = "het spek", categoryName = "Food"),
            Word(english = "the beef", dutch = "het rundvlees", categoryName = "Food"),
            Word(english = "the chicken", dutch = "het kippevlees", categoryName = "Food"),
            Word(english = "the lamb", dutch = "het lamsvlees", categoryName = "Food"),
            Word(english = "the sausage", dutch = "de worst", categoryName = "Food"),
            Word(english = "the steak", dutch = "de biefstuk", categoryName = "Food"),
            Word(english = "the veal", dutch = "het kalfsvlees", categoryName = "Food"),
            Word(english = "the bath", dutch = "Het bad", categoryName = "House"),
            Word(english = "the soap", dutch = "De zeep", categoryName = "House"),
            Word(english = "the toilet paper", dutch = "Het toiletpapier", categoryName = "House"),
            Word(english = "the toothbrush", dutch = "De tandenborstel", categoryName = "House"),
            Word(english = "the toothpaste", dutch = "De tandpasta", categoryName = "House"),
            Word(english = "the towel", dutch = "De handdoek", categoryName = "House"),
            Word(english = "the washbasin", dutch = "De wastafel", categoryName = "House"),
            Word(english = "the alarm clock", dutch = "De wekker", categoryName = "House"),
            Word(english = "the bed", dutch = "Het bed", categoryName = "House"),
            Word(english = "the bedroom", dutch = "De slaapkamer", categoryName = "House"),
            Word(english = "the blanket", dutch = "De deken", categoryName = "House"),
            Word(english = "the mattress", dutch = "Het matras", categoryName = "House"),
            Word(english = "the pillow", dutch = "Het kussen", categoryName = "House"),
            Word(english = "the pillow case", dutch = "Het kussensloop", categoryName = "House"),
            Word(english = "the sheet", dutch = "Het laken", categoryName = "House"),
            Word(english = "a knife", dutch = "een mes", categoryName = "House"),
            Word(english = "a fork", dutch = "een vork", categoryName = "House"),
            Word(english = "a spoon", dutch = "een lepel", categoryName = "House"),
            Word(english = "a serviette", dutch = "een servet", categoryName = "House"),
            Word(english = "the chair", dutch = "De stoel", categoryName = "House"),
            Word(english = "the clock", dutch = "De klok", categoryName = "House"),
            Word(english = "the cupboard", dutch = "De kast", categoryName = "House"),
            Word(english = "the light", dutch = "Het licht", categoryName = "House"),
            Word(english = "the key", dutch = "De sleutel", categoryName = "House"),
            Word(english = "the radio", dutch = "De radio", categoryName = "House"),
            Word(english = "the sofa", dutch = "De bank", categoryName = "House"),
            Word(english = "the table", dutch = "De tafel", categoryName = "House"),
            Word(english = "the bathroom", dutch = "de badkamer", categoryName = "House"),
            Word(english = "the bedroom", dutch = "de slaapkamer", categoryName = "House"),
            Word(english = "the door", dutch = "de deur", categoryName = "House"),
            Word(english = "the kitchen", dutch = "de keuken", categoryName = "House"),
            Word(english = "the living room", dutch = "de zitkamer", categoryName = "House"),
            Word(english = "the room", dutch = "de kamer", categoryName = "House"),
            Word(english = "the stairs", dutch = "de trap", categoryName = "House"),
            Word(english = "the window", dutch = "het raam", categoryName = "House"),
            Word(english = "one", dutch = "Eén", categoryName = "Number"),
            Word(english = "two", dutch = "twee", categoryName = "Number"),
            Word(english = "three", dutch = "drie", categoryName = "Number"),
            Word(english = "four", dutch = "vier", categoryName = "Number"),
            Word(english = "five", dutch = "vijf", categoryName = "Number"),
            Word(english = "six", dutch = "zes", categoryName = "Number"),
            Word(english = "seven", dutch = "zeven", categoryName = "Number"),
            Word(english = "eight", dutch = "acht", categoryName = "Number"),
            Word(english = "nine", dutch = "negen", categoryName = "Number"),
            Word(english = "ten", dutch = "tien", categoryName = "Number"),
            Word(english = "eleven", dutch = "elf", categoryName = "Number"),
            Word(english = "twelve", dutch = "twaalf", categoryName = "Number"),
            Word(english = "thirteen", dutch = "dertien", categoryName = "Number"),
            Word(english = "fourteen", dutch = "veertien", categoryName = "Number"),
            Word(english = "fifteen", dutch = "vijftien", categoryName = "Number"),
            Word(english = "sixteen", dutch = "zestien", categoryName = "Number"),
            Word(english = "seventeen", dutch = "zeventien", categoryName = "Number"),
            Word(english = "eighteen", dutch = "achttien", categoryName = "Number"),
            Word(english = "nineteen", dutch = "negentien", categoryName = "Number"),
            Word(english = "twenty", dutch = "twintig", categoryName = "Number"),
            Word(english = "thirty", dutch = "dertig", categoryName = "Number"),
            Word(english = "forty", dutch = "veertig", categoryName = "Number"),
            Word(english = "fifty", dutch = "vijftig", categoryName = "Number"),
            Word(english = "sixty", dutch = "zestig", categoryName = "Number"),
            Word(english = "seventy", dutch = "zeventig", categoryName = "Number"),
            Word(english = "eighty", dutch = "tachtig", categoryName = "Number"),
            Word(english = "ninety", dutch = "negentig", categoryName = "Number"),
            Word(english = "one hundred", dutch = "honderd", categoryName = "Number"),
            Word(english = "one thousand", dutch = "duizend", categoryName = "Number"),
            Word(english = "this week", dutch = "deze week", categoryName = "Time/Date"),
            Word(english = "next week", dutch = "volgende week", categoryName = "Time/Date"),
            Word(english = "yesterday", dutch = "gisteren", categoryName = "Time/Date"),
            Word(english = "today", dutch = "vandaag", categoryName = "Time/Date"),
            Word(english = "tomorrow", dutch = "morgen", categoryName = "Time/Date"),
            Word(english = "now", dutch = "nu", categoryName = "Time/Date"),
            Word(english = "later", dutch = "later", categoryName = "Time/Date"),
            Word(english = "this morning", dutch = "vanmorgen", categoryName = "Time/Date"),
            Word(english = "this afternoon", dutch = "vanmiddag", categoryName = "Time/Date"),
            Word(english = "tonight", dutch = "vanavond", categoryName = "Time/Date"),
            Word(english = "Monday", dutch = "maandag", categoryName = "Time/Date"),
            Word(english = "Tuesday", dutch = "dinsdag", categoryName = "Time/Date"),
            Word(english = "Wednesday", dutch = "woensdag", categoryName = "Time/Date"),
            Word(english = "Thursday", dutch = "donderdag", categoryName = "Time/Date"),
            Word(english = "Friday", dutch = "vrijdag", categoryName = "Time/Date"),
            Word(english = "Saturday", dutch = "zaterdag", categoryName = "Time/Date"),
            Word(english = "January", dutch = "Januari", categoryName = "Time/Date"),
            Word(english = "February", dutch = "Februari", categoryName = "Time/Date"),
            Word(english = "March", dutch = "Maart", categoryName = "Time/Date"),
            Word(english = "April", dutch = "April", categoryName = "Time/Date"),
            Word(english = "May", dutch = "Mei", categoryName = "Time/Date"),
            Word(english = "June", dutch = "Juni", categoryName = "Time/Date"),
            Word(english = "July", dutch = "Juli", categoryName = "Time/Date"),
            Word(english = "August", dutch = "Augustus", categoryName = "Time/Date"),
            Word(english = "September", dutch = "September", categoryName = "Time/Date"),
            Word(english = "October", dutch = "Oktober", categoryName = "Time/Date"),
            Word(english = "November", dutch = "November", categoryName = "Time/Date"),
            Word(english = "December", dutch = "December", categoryName = "Time/Date"),
            Word(english = "It is one o'clock", dutch = "Het is één uur", categoryName = "Time/Date"),
            Word(english = "It is two o'clock", dutch = "Het is twee uur", categoryName = "Time/Date"),
            Word(english = "It is three o'clock", dutch = "Het is drie uur", categoryName = "Time/Date"),
            Word(english = "It is four o'clock", dutch = "Het is vier uur", categoryName = "Time/Date"),
            Word(english = "It is five o'clock", dutch = "Het is vijf uur", categoryName = "Time/Date"),
            Word(english = "It is six o'clock", dutch = "Het is zes uur", categoryName = "Time/Date"),
            Word(english = "It is seven o'clock", dutch = "Het is zeven uur", categoryName = "Time/Date"),
            Word(english = "It is eight o'clock", dutch = "Het is acht uur", categoryName = "Time/Date"),
            Word(english = "It is nine o'clock", dutch = "Het is negen uur", categoryName = "Time/Date"),
            Word(english = "It is ten o'clock", dutch = "Het is tien uur", categoryName = "Time/Date"),
            Word(english = "It is eleven o'clock", dutch = "Het is elf uur", categoryName = "Time/Date"),
            Word(english = "It is twelve o'clock", dutch = "Het is twaalf uur", categoryName = "Time/Date"),
            Word(english = "I want to buy ..", dutch = "Ik wil ..", categoryName = ""),
            Word(english = "I'm just looking", dutch = "Ik wil alleen even kijken", categoryName = ""),
            Word(english = "How much is it?", dutch = "Hoeveel kost het?", categoryName = ""),
            Word(english = "It's too expensive", dutch = "Het is te duur", categoryName = ""),
            Word(english = "Do you accept credit cards?", dutch = "Neemt u creditcards aan?", categoryName = ""),
            Word(english = "That's all thanks", dutch = "Dat is alles bedankt", categoryName = ""),
            Word(english = "It is faulty", dutch = "Het is kapot", categoryName = ""),
            Word(english = "Will you change it?", dutch = "Kunt u het wisselen?", categoryName = ""),
            Word(english = "I'd like a refund", dutch = "Ik wil graag mijn geld terug", categoryName = ""),
            Word(english = "I would like to try this on", dutch = "Ik zou dit willen passen", categoryName = ""),
            Word(english = "Do you have a larger size?", dutch = "Heeft u een grotere maat?", categoryName = ""),
            Word(english = "Do you have a smaller size?", dutch = "Heeft u een kleinere maat?", categoryName = ""),
            Word(english = "Do you have another colour?", dutch = "Heeft u een andere kleur?", categoryName = ""),
            Word(english = "the map", dutch = "De kaart", categoryName = ""),
            Word(english = "the phone", dutch = "De telefoon", categoryName = ""),
            Word(english = "the phone card", dutch = "De telefoonkaart", categoryName = ""),
            Word(english = "the postcard", dutch = "De ansichtkaart", categoryName = ""),
            Word(english = "the souvenir", dutch = "Het souvenier", categoryName = ""),
            Word(english = "the stamp", dutch = "De postzegel", categoryName = ""),
            Word(english = "I'm from ..", dutch = "Ik kom uit ..", categoryName = ""),
            Word(english = "I'm from England", dutch = "Ik kom uit Engeland", categoryName = ""),
            Word(english = "I'm from America", dutch = "Ik kom uit Amerika", categoryName = ""),
            Word(english = "Do you speak English?", dutch = "Spreekt u Engels?", categoryName = ""),
            Word(english = "I don't speak Dutch", dutch = "Ik spreek geen Nederlands", categoryName = ""),
            Word(english = "Could you write it down?", dutch = "Kunt u het opschrijven alstublieft?", categoryName = ""),
            Word(english = "Does anyone speak English?", dutch = "Spreekt er iemand Engels?", categoryName = ""),
            Word(english = "Can you repeat that?", dutch = "Kunt u dat herhalen?", categoryName = ""),
            Word(english = "I don't understand", dutch = "Ik begrijp het niet", categoryName = ""),
            Word(english = "Pardon?", dutch = "Pardon?", categoryName = ""),
            Word(english = "What is it called in Dutch?", dutch = "Hoe heet dit in het Nederlands?", categoryName = ""),
            Word(english = "Please speak more slowly?", dutch = "Spreek u alstublieft wat langzamer", categoryName = ""),
            Word(english = "What does .. mean?", dutch = "Wat betekent ..?", categoryName = ""),
            Word(english = "This is ..", dutch = "Dit is ..", categoryName = ""),
            Word(english = "This is Mr Smith", dutch = "Dit is mijnheer Smith", categoryName = ""),
            Word(english = "This is Mrs Smith", dutch = "Dit is mevrouw Smith", categoryName = ""),
            Word(english = "Where are you from?", dutch = "Waar kom je vandaan?", categoryName = ""),
            Word(english = "Have you been to my country?", dutch = "Bent u wel eens in mijn land geweet?", categoryName = ""),
            Word(english = "I live in ...", dutch = "Ik woon in ...", categoryName = ""),
            Word(english = "What do you think of the city?", dutch = "Wat vind jij van de stad?", categoryName = ""),
            Word(english = "Are you married?", dutch = "Ben je getrouwd?", categoryName = ""),
            Word(english = "I'm single", dutch = "Ik ben vrijgezel", categoryName = ""),
            Word(english = "Where are you staying?", dutch = "Waar logeer je?", categoryName = ""),
            Word(english = "Do you have children?", dutch = "Heb je kinderen?", categoryName = ""),
            Word(english = "What do you do?", dutch = "Wat doe je voor werk?", categoryName = ""),
            Word(english = "I'm retired", dutch = "Ik ben gepensioneerd", categoryName = ""),
            Word(english = "I'm a student", dutch = "Ik ben student", categoryName = ""),
            Word(english = "I'm travelling", dutch = "Ik ben aan het reizen", categoryName = ""),
            Word(english = "I'm here on holiday", dutch = "Ik ben hier op vakantie", categoryName = ""),
            Word(english = "I'm here on business", dutch = "Ik ben hier voor zaken", categoryName = ""),
            Word(english = "Have you been to ...?", dutch = "Ben je in ... geweest?", categoryName = ""),
            Word(english = "I've been to ...", dutch = "Ik ben in ... geweest", categoryName = ""),
            Word(english = "Yes of course!", dutch = "Ja natuurlijk!", categoryName = ""),
            Word(english = "Of course not!", dutch = "Natuurlijk niet!", categoryName = ""),
            Word(english = "You're joking!", dutch = "Je maakt een grapje!", categoryName = ""),
            Word(english = "How's it going?", dutch = "Hoe gaat het?", categoryName = ""),
            Word(english = "No way!", dutch = "Nee hoor!", categoryName = ""),
            Word(english = "My e-mail address is ..", dutch = "Mijn email adres is ..", categoryName = ""),
            Word(english = "What is your e-mail address ..?", dutch = "Wat is jouw email adres?", categoryName = ""),
            Word(english = "Here is my address", dutch = "Hier is mijn adres", categoryName = ""),
            Word(english = "Do you like football?", dutch = "Hou je van voetbal?", categoryName = ""),
            Word(english = "Who do you support?", dutch = "Voor wie ben je?", categoryName = ""),
            Word(english = "Who is your best player?", dutch = "Wie vind je de beste speler?", categoryName = ""),
            Word(english = "I support ..", dutch = "Ik steun ..", categoryName = ""),
            Word(english = "He's a great player", dutch = "Hij is een goede speler", categoryName = ""),
            Word(english = "The coach is ..", dutch = "De trainer is ..", categoryName = ""),
            Word(english = "What's the weather like?", dutch = "Hoe is het weer?", categoryName = ""),
            Word(english = "Is it going to rain?", dutch = "Gaat het regenen?", categoryName = ""),
            Word(english = "It's hot", dutch = "Het is heet", categoryName = ""),
            Word(english = "It's cold", dutch = "Het is koud", categoryName = ""),
            Word(english = "It's nice", dutch = "Het is mooi", categoryName = ""),
            Word(english = "It's freezing", dutch = "Het is ijskoud", categoryName = ""),
            Word(english = "It's windy", dutch = "Het is winderig", categoryName = ""),
            Word(english = "It's rainy", dutch = "Het is regenachtig", categoryName = ""),
            Word(english = "good", dutch = "Goed", categoryName = ""),
            Word(english = "bad", dutch = "Slecht", categoryName = ""),
            Word(english = "hot", dutch = "Heet", categoryName = ""),
            Word(english = "cold", dutch = "Koud", categoryName = ""),
            Word(english = "young", dutch = "Jong", categoryName = ""),
            Word(english = "old", dutch = "Oud", categoryName = ""),
            Word(english = "fast", dutch = "Snel", categoryName = ""),
            Word(english = "slow", dutch = "Langzaam", categoryName = ""),
            Word(english = "clean", dutch = "Schoon", categoryName = ""),
            Word(english = "dirty", dutch = "Vuil", categoryName = ""),
            Word(english = "Where is ..?", dutch = "Waar is ..?", categoryName = ""),
            Word(english = "Where are ..?", dutch = "Waar zijn ..?", categoryName = ""),
            Word(english = "How do I get to ..?", dutch = "Hoe kom ik bij ..?", categoryName = ""),
            Word(english = "Can I walk there?", dutch = "Kan ik daar naar toe lopen?", categoryName = ""),
            Word(english = "Is there a bus?", dutch = "Gaat er een bus?", categoryName = ""),
            Word(english = "Is there a train?", dutch = "Gaat er een trein?", categoryName = ""),
            Word(english = "Is it far?", dutch = "Is het ver?", categoryName = ""),
            Word(english = "Can you show me on the map?", dutch = "Kunt u het mij op de kaart laten zien?", categoryName = ""),
            Word(english = "Is there a .. nearby?", dutch = "Is er een .. in de buurt?", categoryName = ""),
            Word(english = "To the left", dutch = "Linksaf", categoryName = ""),
            Word(english = "To the right", dutch = "Rechtsaf", categoryName = ""),
            Word(english = "here", dutch = "Hier", categoryName = ""),
            Word(english = "there", dutch = "Daar", categoryName = ""),
            Word(english = "On the right hand side", dutch = "Aan de linkerhand", categoryName = ""),
            Word(english = "On the left hand side", dutch = "Aan de rechterhand", categoryName = ""),
            Word(english = "At the end of the street", dutch = "Aan het eind van de straat", categoryName = ""),
            Word(english = "The first on the right", dutch = "De eerste rechts", categoryName = ""),
            Word(english = "The first on the left", dutch = "De eerste links", categoryName = ""),
            Word(english = "Straight on", dutch = "Rechtdoor", categoryName = ""),
            Word(english = "Can we eat?", dutch = "Mogen we iets eten?", categoryName = ""),
            Word(english = "Can we have breakfast?", dutch = "Mogen we een ontbijt?", categoryName = ""),
            Word(english = "Is there a table free?", dutch = "Heeft u een tafel vrij?", categoryName = ""),
            Word(english = "A table for four please", dutch = "Een tafel voor vier alstublieft", categoryName = ""),
            Word(english = "I'd like to book a table for two", dutch = "Ik wil graag een tafel voor twee reserveren", categoryName = ""),
            Word(english = "The menu please", dutch = "De kaart alstublieft", categoryName = ""),
            Word(english = "Have you any vegetarian dishes?", dutch = "Heeft u vegetarische gerechten?", categoryName = ""),
            Word(english = "I'll have ..", dutch = "Ik wil graag ..", categoryName = ""),
            Word(english = "That was delicious", dutch = "Het was heerlijk", categoryName = ""),
            Word(english = "It's delicious!", dutch = "Het is heerlijk!", categoryName = ""),
            Word(english = "It is delicious, but I'm full!", dutch = "Het is heerlijk, maar ik ben vol!", categoryName = ""),
            Word(english = "That's enough, thanks", dutch = "Dat is genoeg, bedankt", categoryName = ""),
            Word(english = "Enjoy your meal!", dutch = "Eet smakelijk!", categoryName = ""),
            Word(english = "This isn't properly cooked", dutch = "Dit is niet goed gekookt", categoryName = ""),
            Word(english = "We didn't order this", dutch = "We hebben dit niet besteld", categoryName = ""),
            Word(english = "We ordered ...", dutch = "We hebben ... besteld", categoryName = ""),
            Word(english = "Where is the toilet please?", dutch = "Waar is het toilet alstublieft?", categoryName = ""),
            Word(english = "I need a Doctor", dutch = "Ik heb een doktor nodig", categoryName = ""),
            Word(english = "I am lost", dutch = "Ik ben verdwaald", categoryName = ""),
            Word(english = "I need help", dutch = "Ik heb hulp nodig", categoryName = ""),
            Word(english = "Help!", dutch = "Help!", categoryName = ""),
            Word(english = "Leave me alone!", dutch = "Laat me met rust!", categoryName = ""),
            Word(english = "I've lost my passport", dutch = "Ik ben mijn paspoort verloren", categoryName = ""),
            Word(english = "Call the police!", dutch = "Bel de politie!", categoryName = ""),
            Word(english = "Call an ambulance!", dutch = "Bel een ambulance!", categoryName = ""),
            Word(english = "Do you have ..?", dutch = "Heeft u ..?", categoryName = ""),
            Word(english = "Is there ..?", dutch = "Is er ..?", categoryName = ""),
            Word(english = "For me", dutch = "Voor mij", categoryName = ""),
            Word(english = "For him", dutch = "Voor hem", categoryName = ""),
            Word(english = "For her", dutch = "Voor haar", categoryName = ""),
            Word(english = "The bill please", dutch = "De rekening alstublieft", categoryName = ""),
            Word(english = "Keep the change", dutch = "Laat maar zitten", categoryName = ""),
            Word(english = "It's my round", dutch = "Dit rondje is van mij", categoryName = ""),
            Word(english = "What would you like to drink?", dutch = "Wat wil je drinken?", categoryName = ""),
            Word(english = "Cheers!", dutch = "Proost!", categoryName = ""),
            Word(english = "I'm feeling drunk!", dutch = "Ik ben een beetje dronken", categoryName = ""),
            Word(english = "I feel ill", dutch = "Ik voel me ziek", categoryName = ""),
            Word(english = "The wine list please", dutch = "De wijnkaart alstublieft", categoryName = ""),
            Word(english = "Same again please", dutch = "Hetzelfde nog een keer alstublieft", categoryName = ""),
            Word(english = "Do you have a map of ..?", dutch = "Heeft u een kaart van ..?", categoryName = ""),
            Word(english = "How long does it take to get to ..?", dutch = "Hoe lang is het naar ..?", categoryName = ""),
            Word(english = "Is this seat occupied?", dutch = "Is deze plaats bezet?", categoryName = ""),
            Word(english = "Do I need to change?", dutch = "Moet ik overstappen?", categoryName = ""),
            Word(english = "A single ticket", dutch = "Een enkele reis", categoryName = ""),
            Word(english = "A return ticket", dutch = "Een retourtje", categoryName = ""),
            Word(english = "Is there a discount for children?", dutch = "Krijgen kinderen korting?", categoryName = ""),
            Word(english = "Is there a discount for pensioners?", dutch = "Krijgen ouderen korting?", categoryName = ""),
            Word(english = "A ticket for ..", dutch = "Een kaartje naar ..", categoryName = ""),
            Word(english = "Is this the train for ..?", dutch = "Gaat deze trein naar ..?", categoryName = ""),
            Word(english = "When does the train leave?", dutch = "Wanneer vertrekt de trein?", categoryName = ""),
            Word(english = "What platform does the train leave from?", dutch = "Van welk perron vertrekt de trein?", categoryName = ""),
            Word(english = "The bus stop", dutch = "De bushalte", categoryName = ""),
            Word(english = "When is the next bus?", dutch = "Wanneer is de volgende bus?", categoryName = ""),
            Word(english = "When is the last bus?", dutch = "Wanneer is de laatste bus?", categoryName = ""),
            Word(english = "What time does it leave?", dutch = "Hoe laat vertrekt hij?", categoryName = ""),
            Word(english = "When does it arrive?", dutch = "Hoe laat komt hij aan?", categoryName = ""),
            Word(english = "Is this taxi occupied?", dutch = "Is deze taxi bezet?", categoryName = ""),
            Word(english = "I want to go to ..", dutch = "Ik wil naar ..", categoryName = ""),
            Word(english = "How much to go to ..?", dutch = "Hoe veel kost het naar ..?", categoryName = ""),
            Word(english = "It's near here", dutch = "Het is hier dichtbij", categoryName = ""),
            Word(english = "Will you slow down", dutch = "Kunt u iets langzamer rijden", categoryName = ""),
            Word(english = "Stop here", dutch = "Hier stoppen", categoryName = ""),
            Word(english = "Can you turn the meter on?", dutch = "Kunt u de meter aanzetten?", categoryName = ""),
            Word(english = "Do you have a road map?", dutch = "Heeft u een wegenkaart?", categoryName = ""),
            Word(english = "Please fill the tank", dutch = "Volgooien alstublieft", categoryName = ""),
            Word(english = "Will you check the tyre pressure?", dutch = "Kunt u de bandenspanning controleren?", categoryName = ""),
            Word(english = "Will you check the headlights?", dutch = "Kunt u de koplampen controleren?", categoryName = ""),
            Word(english = "My car's broken down", dutch = "Mijn auto is kapot", categoryName = ""),
            Word(english = "Can you repair it?", dutch = "Kunt u het repareren?", categoryName = ""),
            Word(english = "I've got a puncture", dutch = "Ik heb een lekke band", categoryName = ""),
            Word(english = "I've run out of petrol", dutch = "Ik heb geen benzine meer", categoryName = ""),
            Word(english = "I've had an accident", dutch = "Ik heb een ongeluk gehad", categoryName = ""),
            Word(english = "Is there a bed and breakfast nearby?", dutch = "Is er een pension in de buurt?", categoryName = ""),
            Word(english = "Is there a station nearby?", dutch = "Is er een station in de buurt?", categoryName = ""),
            Word(english = "Is there a campsite nearby?", dutch = "Is er een camping in de buurt?", categoryName = ""),
            Word(english = "Where can I check my e-mail?", dutch = "Waar kan ik mijn email nakijken?", categoryName = ""),
            Word(english = "Where can I get internet access?", dutch = "Waar kan ik internetten?", categoryName = ""),
            Word(english = "Is it safe to swim here?", dutch = "Kun je veilig zwemmen hier?", categoryName = ""),
            Word(english = "I have a headache", dutch = "Ik heb hoofdpijn", categoryName = ""),
            Word(english = "I have a sore throat", dutch = "Ik heb een zere keel", categoryName = ""),
            Word(english = "I feel sick", dutch = "Ik voel me niet lekker", categoryName = ""),
            Word(english = "I have a cold", dutch = "Ik ben verkouden", categoryName = ""),
            Word(english = "I have diarrhoea", dutch = "Ik heb diarree", categoryName = ""),
            Word(english = "I've been stung by a bee", dutch = "Ik ben door een bij gestoken", categoryName = ""),
            Word(english = "I have sunstroke", dutch = "Ik heb een zonnesteek", categoryName = ""),
            Word(english = "I have dizzy spells", dutch = "Ik voel me duizelig", categoryName = ""),
            Word(english = "the bookcase", dutch = "De boekenkast", categoryName = ""),
            Word(english = "the picture", dutch = "Het schilderij", categoryName = ""),
            Word(english = "The money", dutch = "Het geld", categoryName = ""),
            Word(english = "The credit card", dutch = "De creditcard", categoryName = ""),
            Word(english = "Where can I change money?", dutch = "Waar kan ik geld wisselen?", categoryName = ""),
            Word(english = "Is there a bank nearby?", dutch = "Is er een bank in de buurt?", categoryName = ""),
            Word(english = "What is the exchange rate?", dutch = "Wat is de wisselkoers?", categoryName = ""),
            Word(english = "I'd like to change some pounds", dutch = "Ik wil een paar ponden wisselen", categoryName = ""),
            Word(english = "I'd like to change some dollars", dutch = "Ik wil een paar dollars wisselen", categoryName = ""),
            Word(english = "Please give me some small change", dutch = "Kunt u me kleingeld geven alstublieft", categoryName = ""),
            Word(english = "Please will you give me a receipt", dutch = "Kunt u me een bonnetje geven alstublieft", categoryName = ""),
            Word(english = "the arm", dutch = "de arm", categoryName = ""),
            Word(english = "the finger", dutch = "de vinger", categoryName = ""),
            Word(english = "the face", dutch = "het gezicht", categoryName = ""),
            Word(english = "the foot", dutch = "de voet", categoryName = ""),
            Word(english = "the head", dutch = "het hoofd", categoryName = ""),
            Word(english = "the leg", dutch = "het been", categoryName = ""),
            Word(english = "the mouth", dutch = "de mond", categoryName = ""),
            Word(english = "the stomach", dutch = "de maag", categoryName = ""),
            Word(english = "the thumb", dutch = "de duim", categoryName = ""),
            Word(english = "the airport", dutch = "De luchthaven", categoryName = ""),
            Word(english = "the baker's shop", dutch = "De bakkerij", categoryName = ""),
            Word(english = "the bank", dutch = "De bank", categoryName = ""),
            Word(english = "the beach", dutch = "Het strand", categoryName = ""),
            Word(english = "the cafe", dutch = "Het café", categoryName = ""),
            Word(english = "the campsite", dutch = "De camping", categoryName = ""),
            Word(english = "the cathedral", dutch = "De kathedraal", categoryName = ""),
            Word(english = "the chemist's", dutch = "De apotheek", categoryName = ""),
            Word(english = "the church", dutch = "De kerk", categoryName = ""),
            Word(english = "the hospital", dutch = "Het ziekenhuis", categoryName = ""),
            Word(english = "the hotel", dutch = "Het hotel", categoryName = ""),
            Word(english = "the laundrette", dutch = "De wasserette", categoryName = ""),
            Word(english = "the market", dutch = "De markt", categoryName = ""),
            Word(english = "the police station", dutch = "Het politiebureau", categoryName = ""),
            Word(english = "the post office", dutch = "Het postkantoor", categoryName = ""),
            Word(english = "the road", dutch = "De weg", categoryName = ""),
            Word(english = "the street", dutch = "De straat", categoryName = ""),
            Word(english = "the swimming pool", dutch = "Het zwembad", categoryName = ""),
            Word(english = "the supermarket", dutch = "De supermarkt", categoryName = ""),
            Word(english = "the tourist office", dutch = "Het VVV kantoor", categoryName = ""),
            Word(english = "the town centre", dutch = "Het centrum van de stad", categoryName = ""),
            Word(english = "Who?", dutch = "Wie?", categoryName = ""),
            Word(english = "Where?", dutch = "Waar?", categoryName = ""),
            Word(english = "What?", dutch = "Wat?", categoryName = ""),
            Word(english = "Why?", dutch = "Waarom?", categoryName = ""),
            Word(english = "When?", dutch = "Wanneer?", categoryName = ""),
            Word(english = "How?", dutch = "Hoe?", categoryName = ""),
            Word(english = "large", dutch = "groot", categoryName = ""),
            Word(english = "small", dutch = "klein", categoryName = ""),
            Word(english = "more", dutch = "meer", categoryName = ""),
            Word(english = "less", dutch = "minder", categoryName = ""),
            Word(english = "I have booked a room", dutch = "Ik heb een kamer gereserveerd", categoryName = ""),
            Word(english = "I haven't booked a room", dutch = "Ik heb geen kamer gereserveerd", categoryName = ""),
            Word(english = "I would like a single room", dutch = "Ik wil een éénpersoonskamer", categoryName = ""),
            Word(english = "I would like a double room", dutch = "Ik wil een tweepersoonskamer", categoryName = ""),
            Word(english = "For three nights", dutch = "Voor drie nachten", categoryName = ""),
            Word(english = "How much is it per night?", dutch = "Hoeveel kost het per nacht?", categoryName = ""),
            Word(english = "Can I see it?", dutch = "Kan ik even kijken?", categoryName = ""),
            Word(english = "I like the room", dutch = "Ik vind de kamer mooi", categoryName = ""),
            Word(english = "I don't like it", dutch = "Ik vind hem niet mooi", categoryName = ""),
            Word(english = "I'll take it", dutch = "Ik neem hem", categoryName = ""),
            Word(english = "A room with en suite", dutch = "Een kamer en suite", categoryName = ""),
            Word(english = "A reservation", dutch = "Een reservering", categoryName = ""),
            Word(english = "It is too expensive", dutch = "Het is te duur", categoryName = ""),
            Word(english = "Have you got something cheaper?", dutch = "Heeft u iets goedkopers?", categoryName = ""),
            Word(english = "Is there air conditioning?", dutch = "Is er airconditioning?", categoryName = ""),
            Word(english = "The air conditioning is not working", dutch = "De airconditioning doet het niet", categoryName = ""),
            Word(english = "Will you give me an extra pillow?", dutch = "Kunt u me een extra kussen geven?", categoryName = ""),
            Word(english = "Can I have some toilet paper?", dutch = "Mag ik wat toiletpapier?", categoryName = ""),
            Word(english = "Can I pay by credit card?", dutch = "Kan ik met creditcard betalen?", categoryName = ""),
            Word(english = "Can I pay by traveler's cheque?", dutch = "Kan ik met traveller's cheques betalen?", categoryName = ""),
            Word(english = "There's a mistake in the bill", dutch = "Er staat een foutje op de rekening", categoryName = ""),
            Word(english = "We've enjoyed our stay", dutch = "We vonden het leuk hier te zijn", categoryName = ""),
            Word(english = "the basement", dutch = "de kelder", categoryName = ""),
            Word(english = "What time is it?", dutch = "Hoe laat is het?", categoryName = ""),
            Word(english = "Customs", dutch = "Douane", categoryName = ""),
            Word(english = "Exit", dutch = "Uitgang", categoryName = ""),
            Word(english = "Entrance", dutch = "Ingang", categoryName = ""),
            Word(english = "Toilet", dutch = "Toilet", categoryName = ""),
            Word(english = "Open", dutch = "Open", categoryName = ""),
            Word(english = "Closed", dutch = "Gesloten", categoryName = ""))
}