package fr.arnaud_camus.leren

import android.app.Application
import fr.arnaud_camus.leren.models.Word
import io.realm.Realm
import io.realm.RealmConfiguration

/**
 * Created by arnaud on 3/6/16.
 */
class LerenApplication: Application() {

    override fun onCreate() {
        super.onCreate()
        val realmConfig = RealmConfiguration.Builder(this).build()
        Realm.setDefaultConfiguration(realmConfig)
    }

    val mockData: Array<Word> = arrayOf(Word().initWith("Goodbye", dutch = "Tot ziens", categoryName = "Basics"),
            Word().initWith("Good morning", dutch = "Goedemorgen", categoryName = "Basics"),
            Word().initWith("Good afternoon", dutch = "Goedemiddag", categoryName = "Basics"),
            Word().initWith("Good evening", dutch = "Goedenavond", categoryName = "Basics"),
            Word().initWith("Yes", dutch = "Ja", categoryName = "Basics"),
            Word().initWith("No", dutch = "Nee", categoryName = "Basics"),
            Word().initWith("Please", dutch = "Alsjeblieft", categoryName = "Basics"),
            Word().initWith("Thanks", dutch = "Dankjewel", categoryName = "Basics"),
            Word().initWith("My name is ..", dutch = "Ik heet ..", categoryName = "Basics"),
            Word().initWith("What is your name?", dutch = "Hoe heet jij?", categoryName = "Basics"),
            Word().initWith("How are you?", dutch = "Hoe gaat het met jou?", categoryName = "Basics"),
            Word().initWith("Fine and you?", dutch = "Goed en met jou?", categoryName = "Basics"),
            Word().initWith("Pleased to meet you", dutch = "Aangenaam kennis te maken", categoryName = "Basics"),
            Word().initWith("See you later", dutch = "Tot ziens", categoryName = "Basics"),
            Word().initWith("Sorry", dutch = "Sorry", categoryName = "Basics"),
            Word().initWith("Excuse me", dutch = "Pardon", categoryName = "Basics"),
            Word().initWith("Can you help me please?", dutch = "Kun je me helpen alsjeblieft?", categoryName = "Basics"),
            Word().initWith("I am trying to learn Dutch", dutch = "Ik probeer Nederlands te leren", categoryName = "Basics"),
            Word().initWith("Sunday", dutch = "zondag", categoryName = "Color"),
            Word().initWith("It is red", dutch = "Het is rood", categoryName = "Color"),
            Word().initWith("It is blue", dutch = "Het is blauw", categoryName = "Color"),
            Word().initWith("black", dutch = "Zwart", categoryName = "Color"),
            Word().initWith("blue", dutch = "Blauw", categoryName = "Color"),
            Word().initWith("green", dutch = "Groen", categoryName = "Color"),
            Word().initWith("orange", dutch = "Oranje", categoryName = "Color"),
            Word().initWith("purple", dutch = "Paars", categoryName = "Color"),
            Word().initWith("red", dutch = "Rood", categoryName = "Color"),
            Word().initWith("yellow", dutch = "Geel", categoryName = "Color"),
            Word().initWith("white", dutch = "Wit", categoryName = "Color"),
            Word().initWith("This is my wife", dutch = "Dit is mijn vrouw", categoryName = "Family"),
            Word().initWith("This is my husband", dutch = "Dit is mijn man", categoryName = "Family"),
            Word().initWith("This is my son", dutch = "Dit is mijn zoon", categoryName = "Family"),
            Word().initWith("This is my daughter", dutch = "Dit is mijn dochter", categoryName = "Family"),
            Word().initWith("the father", dutch = "De vader", categoryName = "Family"),
            Word().initWith("the mother", dutch = "De moeder", categoryName = "Family"),
            Word().initWith("the husband", dutch = "De echtgenoot", categoryName = "Family"),
            Word().initWith("the wife", dutch = "De echtgenote", categoryName = "Family"),
            Word().initWith("the brother", dutch = "De broer", categoryName = "Family"),
            Word().initWith("the sister", dutch = "De zus", categoryName = "Family"),
            Word().initWith("the son", dutch = "De zoon", categoryName = "Family"),
            Word().initWith("the daughter", dutch = "De dochter", categoryName = "Family"),
            Word().initWith("the girlfriend", dutch = "De vriendin", categoryName = "Family"),
            Word().initWith("the boyfriend", dutch = "De vriend", categoryName = "Family"),
            Word().initWith("the coffee", dutch = "De koffie", categoryName = "Food"),
            Word().initWith("the milk", dutch = "De melk", categoryName = "Food"),
            Word().initWith("For the first course", dutch = "Als voorgerecht", categoryName = "Food"),
            Word().initWith("For the second course", dutch = "Als hoofdgerecht", categoryName = "Food"),
            Word().initWith("For dessert", dutch = "Als dessert", categoryName = "Food"),
            Word().initWith("I don't eat meat", dutch = "Ik eet geen vlees", categoryName = "Food"),
            Word().initWith("the salt", dutch = "het zout", categoryName = "Food"),
            Word().initWith("the pepper", dutch = "de peper", categoryName = "Food"),
            Word().initWith("the sugar", dutch = "de suiker", categoryName = "Food"),
            Word().initWith("the vinegar", dutch = "de azijn", categoryName = "Food"),
            Word().initWith("the sauce", dutch = "de saus", categoryName = "Food"),
            Word().initWith("the mustard", dutch = "de moster", categoryName = "Food"),
            Word().initWith("Is food available here?", dutch = "Heeft u iets te eten hier?", categoryName = "Food"),
            Word().initWith("What sandwiches do you have?", dutch = "Wat voor broodjes heeft u?", categoryName = "Food"),
            Word().initWith("A black coffee please", dutch = "Een zwarte koffie alstublieft", categoryName = "Food"),
            Word().initWith("A white coffee please", dutch = "Een koffie met melk alstublieft", categoryName = "Food"),
            Word().initWith("Two white coffees please", dutch = "Twee koffie met melk alstublieft", categoryName = "Food"),
            Word().initWith("A tea with milk", dutch = "Een thee met melk", categoryName = "Food"),
            Word().initWith("A lemon tea", dutch = "Een thee met citroen", categoryName = "Food"),
            Word().initWith("A lemonade please", dutch = "Een limonade alstublieft", categoryName = "Food"),
            Word().initWith("A beer please", dutch = "Een bier alstublieft", categoryName = "Food"),
            Word().initWith("Two beers", dutch = "Twee bier", categoryName = "Food"),
            Word().initWith("A glass of red wine", dutch = "Een glas rode wijn", categoryName = "Food"),
            Word().initWith("A glass of white wine", dutch = "Een glas witte wijn", categoryName = "Food"),
            Word().initWith("A bottle of house white wine", dutch = "Een fles witte huiswijn", categoryName = "Food"),
            Word().initWith("A bottle of house red wine", dutch = "Een fles rode huiswijn", categoryName = "Food"),
            Word().initWith("A gin and tonic please", dutch = "Een gin-tonic alstublieft", categoryName = "Food"),
            Word().initWith("An orange juice please", dutch = "Een sinaasappelsap alstublieft", categoryName = "Food"),
            Word().initWith("With ice", dutch = "Met ijs", categoryName = "Food"),
            Word().initWith("A mineral water", dutch = "Een spa", categoryName = "Food"),
            Word().initWith("sparkling", dutch = "Met prik", categoryName = "Food"),
            Word().initWith("still", dutch = "Zonder prik", categoryName = "Food"),
            Word().initWith("vodka", dutch = "Wodka", categoryName = "Food"),
            Word().initWith("the bread", dutch = "het brood", categoryName = "Food"),
            Word().initWith("the butter", dutch = "de boter", categoryName = "Food"),
            Word().initWith("the cheese", dutch = "de kaas", categoryName = "Food"),
            Word().initWith("the chips", dutch = "de friet", categoryName = "Food"),
            Word().initWith("the egg", dutch = "het ei", categoryName = "Food"),
            Word().initWith("the ice-cream", dutch = "het ijsje", categoryName = "Food"),
            Word().initWith("an omelette", dutch = "de omelet", categoryName = "Food"),
            Word().initWith("the rice", dutch = "de rijst", categoryName = "Food"),
            Word().initWith("the salad", dutch = "de salade", categoryName = "Food"),
            Word().initWith("the soup", dutch = "de soep", categoryName = "Food"),
            Word().initWith("the apple", dutch = "de appel", categoryName = "Food"),
            Word().initWith("the banana", dutch = "de banaan", categoryName = "Food"),
            Word().initWith("the cherry", dutch = "de kers", categoryName = "Food"),
            Word().initWith("the grape", dutch = "de druif", categoryName = "Food"),
            Word().initWith("the lemon", dutch = "de citroen", categoryName = "Food"),
            Word().initWith("the melon", dutch = "de meloen", categoryName = "Food"),
            Word().initWith("the orange", dutch = "de sinaasappel", categoryName = "Food"),
            Word().initWith("the peach", dutch = "de perzik", categoryName = "Food"),
            Word().initWith("the pear", dutch = "de peer", categoryName = "Food"),
            Word().initWith("the pineapple", dutch = "de ananas", categoryName = "Food"),
            Word().initWith("the carrot", dutch = "de wortel", categoryName = "Food"),
            Word().initWith("the cucumber", dutch = "de komkommer", categoryName = "Food"),
            Word().initWith("the garlic", dutch = "het knoflook", categoryName = "Food"),
            Word().initWith("the lettuce", dutch = "de sla", categoryName = "Food"),
            Word().initWith("the mushroom", dutch = "de champignon", categoryName = "Food"),
            Word().initWith("the pea", dutch = "de erwt", categoryName = "Food"),
            Word().initWith("the onion", dutch = "de ui", categoryName = "Food"),
            Word().initWith("the potato", dutch = "de aardappel", categoryName = "Food"),
            Word().initWith("the tomato", dutch = "de tomaat", categoryName = "Food"),
            Word().initWith("the bacon", dutch = "het spek", categoryName = "Food"),
            Word().initWith("the beef", dutch = "het rundvlees", categoryName = "Food"),
            Word().initWith("the chicken", dutch = "het kippevlees", categoryName = "Food"),
            Word().initWith("the lamb", dutch = "het lamsvlees", categoryName = "Food"),
            Word().initWith("the sausage", dutch = "de worst", categoryName = "Food"),
            Word().initWith("the steak", dutch = "de biefstuk", categoryName = "Food"),
            Word().initWith("the veal", dutch = "het kalfsvlees", categoryName = "Food"),
            Word().initWith("the bath", dutch = "Het bad", categoryName = "House"),
            Word().initWith("the soap", dutch = "De zeep", categoryName = "House"),
            Word().initWith("the toilet paper", dutch = "Het toiletpapier", categoryName = "House"),
            Word().initWith("the toothbrush", dutch = "De tandenborstel", categoryName = "House"),
            Word().initWith("the toothpaste", dutch = "De tandpasta", categoryName = "House"),
            Word().initWith("the towel", dutch = "De handdoek", categoryName = "House"),
            Word().initWith("the washbasin", dutch = "De wastafel", categoryName = "House"),
            Word().initWith("the alarm clock", dutch = "De wekker", categoryName = "House"),
            Word().initWith("the bed", dutch = "Het bed", categoryName = "House"),
            Word().initWith("the bedroom", dutch = "De slaapkamer", categoryName = "House"),
            Word().initWith("the blanket", dutch = "De deken", categoryName = "House"),
            Word().initWith("the mattress", dutch = "Het matras", categoryName = "House"),
            Word().initWith("the pillow", dutch = "Het kussen", categoryName = "House"),
            Word().initWith("the pillow case", dutch = "Het kussensloop", categoryName = "House"),
            Word().initWith("the sheet", dutch = "Het laken", categoryName = "House"),
            Word().initWith("a knife", dutch = "een mes", categoryName = "House"),
            Word().initWith("a fork", dutch = "een vork", categoryName = "House"),
            Word().initWith("a spoon", dutch = "een lepel", categoryName = "House"),
            Word().initWith("a serviette", dutch = "een servet", categoryName = "House"),
            Word().initWith("the chair", dutch = "De stoel", categoryName = "House"),
            Word().initWith("the clock", dutch = "De klok", categoryName = "House"),
            Word().initWith("the cupboard", dutch = "De kast", categoryName = "House"),
            Word().initWith("the light", dutch = "Het licht", categoryName = "House"),
            Word().initWith("the key", dutch = "De sleutel", categoryName = "House"),
            Word().initWith("the radio", dutch = "De radio", categoryName = "House"),
            Word().initWith("the sofa", dutch = "De bank", categoryName = "House"),
            Word().initWith("the table", dutch = "De tafel", categoryName = "House"),
            Word().initWith("the bathroom", dutch = "de badkamer", categoryName = "House"),
            Word().initWith("the bedroom", dutch = "de slaapkamer", categoryName = "House"),
            Word().initWith("the door", dutch = "de deur", categoryName = "House"),
            Word().initWith("the kitchen", dutch = "de keuken", categoryName = "House"),
            Word().initWith("the living room", dutch = "de zitkamer", categoryName = "House"),
            Word().initWith("the room", dutch = "de kamer", categoryName = "House"),
            Word().initWith("the stairs", dutch = "de trap", categoryName = "House"),
            Word().initWith("the window", dutch = "het raam", categoryName = "House"),
            Word().initWith("one", dutch = "Eén", categoryName = "Number"),
            Word().initWith("two", dutch = "twee", categoryName = "Number"),
            Word().initWith("three", dutch = "drie", categoryName = "Number"),
            Word().initWith("four", dutch = "vier", categoryName = "Number"),
            Word().initWith("five", dutch = "vijf", categoryName = "Number"),
            Word().initWith("six", dutch = "zes", categoryName = "Number"),
            Word().initWith("seven", dutch = "zeven", categoryName = "Number"),
            Word().initWith("eight", dutch = "acht", categoryName = "Number"),
            Word().initWith("nine", dutch = "negen", categoryName = "Number"),
            Word().initWith("ten", dutch = "tien", categoryName = "Number"),
            Word().initWith("eleven", dutch = "elf", categoryName = "Number"),
            Word().initWith("twelve", dutch = "twaalf", categoryName = "Number"),
            Word().initWith("thirteen", dutch = "dertien", categoryName = "Number"),
            Word().initWith("fourteen", dutch = "veertien", categoryName = "Number"),
            Word().initWith("fifteen", dutch = "vijftien", categoryName = "Number"),
            Word().initWith("sixteen", dutch = "zestien", categoryName = "Number"),
            Word().initWith("seventeen", dutch = "zeventien", categoryName = "Number"),
            Word().initWith("eighteen", dutch = "achttien", categoryName = "Number"),
            Word().initWith("nineteen", dutch = "negentien", categoryName = "Number"),
            Word().initWith("twenty", dutch = "twintig", categoryName = "Number"),
            Word().initWith("thirty", dutch = "dertig", categoryName = "Number"),
            Word().initWith("forty", dutch = "veertig", categoryName = "Number"),
            Word().initWith("fifty", dutch = "vijftig", categoryName = "Number"),
            Word().initWith("sixty", dutch = "zestig", categoryName = "Number"),
            Word().initWith("seventy", dutch = "zeventig", categoryName = "Number"),
            Word().initWith("eighty", dutch = "tachtig", categoryName = "Number"),
            Word().initWith("ninety", dutch = "negentig", categoryName = "Number"),
            Word().initWith("one hundred", dutch = "honderd", categoryName = "Number"),
            Word().initWith("one thousand", dutch = "duizend", categoryName = "Number"),
            Word().initWith("this week", dutch = "deze week", categoryName = "Time/Date"),
            Word().initWith("next week", dutch = "volgende week", categoryName = "Time/Date"),
            Word().initWith("yesterday", dutch = "gisteren", categoryName = "Time/Date"),
            Word().initWith("today", dutch = "vandaag", categoryName = "Time/Date"),
            Word().initWith("tomorrow", dutch = "morgen", categoryName = "Time/Date"),
            Word().initWith("now", dutch = "nu", categoryName = "Time/Date"),
            Word().initWith("later", dutch = "later", categoryName = "Time/Date"),
            Word().initWith("this morning", dutch = "vanmorgen", categoryName = "Time/Date"),
            Word().initWith("this afternoon", dutch = "vanmiddag", categoryName = "Time/Date"),
            Word().initWith("tonight", dutch = "vanavond", categoryName = "Time/Date"),
            Word().initWith("Monday", dutch = "maandag", categoryName = "Time/Date"),
            Word().initWith("Tuesday", dutch = "dinsdag", categoryName = "Time/Date"),
            Word().initWith("Wednesday", dutch = "woensdag", categoryName = "Time/Date"),
            Word().initWith("Thursday", dutch = "donderdag", categoryName = "Time/Date"),
            Word().initWith("Friday", dutch = "vrijdag", categoryName = "Time/Date"),
            Word().initWith("Saturday", dutch = "zaterdag", categoryName = "Time/Date"),
            Word().initWith("January", dutch = "Januari", categoryName = "Time/Date"),
            Word().initWith("February", dutch = "Februari", categoryName = "Time/Date"),
            Word().initWith("March", dutch = "Maart", categoryName = "Time/Date"),
            Word().initWith("April", dutch = "April", categoryName = "Time/Date"),
            Word().initWith("May", dutch = "Mei", categoryName = "Time/Date"),
            Word().initWith("June", dutch = "Juni", categoryName = "Time/Date"),
            Word().initWith("July", dutch = "Juli", categoryName = "Time/Date"),
            Word().initWith("August", dutch = "Augustus", categoryName = "Time/Date"),
            Word().initWith("September", dutch = "September", categoryName = "Time/Date"),
            Word().initWith("October", dutch = "Oktober", categoryName = "Time/Date"),
            Word().initWith("November", dutch = "November", categoryName = "Time/Date"),
            Word().initWith("December", dutch = "December", categoryName = "Time/Date"),
            Word().initWith("It is one o'clock", dutch = "Het is één uur", categoryName = "Time/Date"),
            Word().initWith("It is two o'clock", dutch = "Het is twee uur", categoryName = "Time/Date"),
            Word().initWith("It is three o'clock", dutch = "Het is drie uur", categoryName = "Time/Date"),
            Word().initWith("It is four o'clock", dutch = "Het is vier uur", categoryName = "Time/Date"),
            Word().initWith("It is five o'clock", dutch = "Het is vijf uur", categoryName = "Time/Date"),
            Word().initWith("It is six o'clock", dutch = "Het is zes uur", categoryName = "Time/Date"),
            Word().initWith("It is seven o'clock", dutch = "Het is zeven uur", categoryName = "Time/Date"),
            Word().initWith("It is eight o'clock", dutch = "Het is acht uur", categoryName = "Time/Date"),
            Word().initWith("It is nine o'clock", dutch = "Het is negen uur", categoryName = "Time/Date"),
            Word().initWith("It is ten o'clock", dutch = "Het is tien uur", categoryName = "Time/Date"),
            Word().initWith("It is eleven o'clock", dutch = "Het is elf uur", categoryName = "Time/Date"),
            Word().initWith("It is twelve o'clock", dutch = "Het is twaalf uur", categoryName = "Time/Date"),
            Word().initWith("I want to buy ..", dutch = "Ik wil ..", categoryName = ""),
            Word().initWith("I'm just looking", dutch = "Ik wil alleen even kijken", categoryName = ""),
            Word().initWith("How much is it?", dutch = "Hoeveel kost het?", categoryName = ""),
            Word().initWith("It's too expensive", dutch = "Het is te duur", categoryName = ""),
            Word().initWith("Do you accept credit cards?", dutch = "Neemt u creditcards aan?", categoryName = ""),
            Word().initWith("That's all thanks", dutch = "Dat is alles bedankt", categoryName = ""),
            Word().initWith("It is faulty", dutch = "Het is kapot", categoryName = ""),
            Word().initWith("Will you change it?", dutch = "Kunt u het wisselen?", categoryName = ""),
            Word().initWith("I'd like a refund", dutch = "Ik wil graag mijn geld terug", categoryName = ""),
            Word().initWith("I would like to try this on", dutch = "Ik zou dit willen passen", categoryName = ""),
            Word().initWith("Do you have a larger size?", dutch = "Heeft u een grotere maat?", categoryName = ""),
            Word().initWith("Do you have a smaller size?", dutch = "Heeft u een kleinere maat?", categoryName = ""),
            Word().initWith("Do you have another colour?", dutch = "Heeft u een andere kleur?", categoryName = ""),
            Word().initWith("the map", dutch = "De kaart", categoryName = ""),
            Word().initWith("the phone", dutch = "De telefoon", categoryName = ""),
            Word().initWith("the phone card", dutch = "De telefoonkaart", categoryName = ""),
            Word().initWith("the postcard", dutch = "De ansichtkaart", categoryName = ""),
            Word().initWith("the souvenir", dutch = "Het souvenier", categoryName = ""),
            Word().initWith("the stamp", dutch = "De postzegel", categoryName = ""),
            Word().initWith("I'm from ..", dutch = "Ik kom uit ..", categoryName = ""),
            Word().initWith("I'm from England", dutch = "Ik kom uit Engeland", categoryName = ""),
            Word().initWith("I'm from America", dutch = "Ik kom uit Amerika", categoryName = ""),
            Word().initWith("Do you speak English?", dutch = "Spreekt u Engels?", categoryName = ""),
            Word().initWith("I don't speak Dutch", dutch = "Ik spreek geen Nederlands", categoryName = ""),
            Word().initWith("Could you write it down?", dutch = "Kunt u het opschrijven alstublieft?", categoryName = ""),
            Word().initWith("Does anyone speak English?", dutch = "Spreekt er iemand Engels?", categoryName = ""),
            Word().initWith("Can you repeat that?", dutch = "Kunt u dat herhalen?", categoryName = ""),
            Word().initWith("I don't understand", dutch = "Ik begrijp het niet", categoryName = ""),
            Word().initWith("Pardon?", dutch = "Pardon?", categoryName = ""),
            Word().initWith("What is it called in Dutch?", dutch = "Hoe heet dit in het Nederlands?", categoryName = ""),
            Word().initWith("Please speak more slowly?", dutch = "Spreek u alstublieft wat langzamer", categoryName = ""),
            Word().initWith("What does .. mean?", dutch = "Wat betekent ..?", categoryName = ""),
            Word().initWith("This is ..", dutch = "Dit is ..", categoryName = ""),
            Word().initWith("This is Mr Smith", dutch = "Dit is mijnheer Smith", categoryName = ""),
            Word().initWith("This is Mrs Smith", dutch = "Dit is mevrouw Smith", categoryName = ""),
            Word().initWith("Where are you from?", dutch = "Waar kom je vandaan?", categoryName = ""),
            Word().initWith("Have you been to my country?", dutch = "Bent u wel eens in mijn land geweet?", categoryName = ""),
            Word().initWith("I live in ...", dutch = "Ik woon in ...", categoryName = ""),
            Word().initWith("What do you think of the city?", dutch = "Wat vind jij van de stad?", categoryName = ""),
            Word().initWith("Are you married?", dutch = "Ben je getrouwd?", categoryName = ""),
            Word().initWith("I'm single", dutch = "Ik ben vrijgezel", categoryName = ""),
            Word().initWith("Where are you staying?", dutch = "Waar logeer je?", categoryName = ""),
            Word().initWith("Do you have children?", dutch = "Heb je kinderen?", categoryName = ""),
            Word().initWith("What do you do?", dutch = "Wat doe je voor werk?", categoryName = ""),
            Word().initWith("I'm retired", dutch = "Ik ben gepensioneerd", categoryName = ""),
            Word().initWith("I'm a student", dutch = "Ik ben student", categoryName = ""),
            Word().initWith("I'm travelling", dutch = "Ik ben aan het reizen", categoryName = ""),
            Word().initWith("I'm here on holiday", dutch = "Ik ben hier op vakantie", categoryName = ""),
            Word().initWith("I'm here on business", dutch = "Ik ben hier voor zaken", categoryName = ""),
            Word().initWith("Have you been to ...?", dutch = "Ben je in ... geweest?", categoryName = ""),
            Word().initWith("I've been to ...", dutch = "Ik ben in ... geweest", categoryName = ""),
            Word().initWith("Yes of course!", dutch = "Ja natuurlijk!", categoryName = ""),
            Word().initWith("Of course not!", dutch = "Natuurlijk niet!", categoryName = ""),
            Word().initWith("You're joking!", dutch = "Je maakt een grapje!", categoryName = ""),
            Word().initWith("How's it going?", dutch = "Hoe gaat het?", categoryName = ""),
            Word().initWith("No way!", dutch = "Nee hoor!", categoryName = ""),
            Word().initWith("My e-mail address is ..", dutch = "Mijn email adres is ..", categoryName = ""),
            Word().initWith("What is your e-mail address ..?", dutch = "Wat is jouw email adres?", categoryName = ""),
            Word().initWith("Here is my address", dutch = "Hier is mijn adres", categoryName = ""),
            Word().initWith("Do you like football?", dutch = "Hou je van voetbal?", categoryName = ""),
            Word().initWith("Who do you support?", dutch = "Voor wie ben je?", categoryName = ""),
            Word().initWith("Who is your best player?", dutch = "Wie vind je de beste speler?", categoryName = ""),
            Word().initWith("I support ..", dutch = "Ik steun ..", categoryName = ""),
            Word().initWith("He's a great player", dutch = "Hij is een goede speler", categoryName = ""),
            Word().initWith("The coach is ..", dutch = "De trainer is ..", categoryName = ""),
            Word().initWith("What's the weather like?", dutch = "Hoe is het weer?", categoryName = ""),
            Word().initWith("Is it going to rain?", dutch = "Gaat het regenen?", categoryName = ""),
            Word().initWith("It's hot", dutch = "Het is heet", categoryName = ""),
            Word().initWith("It's cold", dutch = "Het is koud", categoryName = ""),
            Word().initWith("It's nice", dutch = "Het is mooi", categoryName = ""),
            Word().initWith("It's freezing", dutch = "Het is ijskoud", categoryName = ""),
            Word().initWith("It's windy", dutch = "Het is winderig", categoryName = ""),
            Word().initWith("It's rainy", dutch = "Het is regenachtig", categoryName = ""),
            Word().initWith("good", dutch = "Goed", categoryName = ""),
            Word().initWith("bad", dutch = "Slecht", categoryName = ""),
            Word().initWith("hot", dutch = "Heet", categoryName = ""),
            Word().initWith("cold", dutch = "Koud", categoryName = ""),
            Word().initWith("young", dutch = "Jong", categoryName = ""),
            Word().initWith("old", dutch = "Oud", categoryName = ""),
            Word().initWith("fast", dutch = "Snel", categoryName = ""),
            Word().initWith("slow", dutch = "Langzaam", categoryName = ""),
            Word().initWith("clean", dutch = "Schoon", categoryName = ""),
            Word().initWith("dirty", dutch = "Vuil", categoryName = ""),
            Word().initWith("Where is ..?", dutch = "Waar is ..?", categoryName = ""),
            Word().initWith("Where are ..?", dutch = "Waar zijn ..?", categoryName = ""),
            Word().initWith("How do I get to ..?", dutch = "Hoe kom ik bij ..?", categoryName = ""),
            Word().initWith("Can I walk there?", dutch = "Kan ik daar naar toe lopen?", categoryName = ""),
            Word().initWith("Is there a bus?", dutch = "Gaat er een bus?", categoryName = ""),
            Word().initWith("Is there a train?", dutch = "Gaat er een trein?", categoryName = ""),
            Word().initWith("Is it far?", dutch = "Is het ver?", categoryName = ""),
            Word().initWith("Can you show me on the map?", dutch = "Kunt u het mij op de kaart laten zien?", categoryName = ""),
            Word().initWith("Is there a .. nearby?", dutch = "Is er een .. in de buurt?", categoryName = ""),
            Word().initWith("To the left", dutch = "Linksaf", categoryName = ""),
            Word().initWith("To the right", dutch = "Rechtsaf", categoryName = ""),
            Word().initWith("here", dutch = "Hier", categoryName = ""),
            Word().initWith("there", dutch = "Daar", categoryName = ""),
            Word().initWith("On the right hand side", dutch = "Aan de linkerhand", categoryName = ""),
            Word().initWith("On the left hand side", dutch = "Aan de rechterhand", categoryName = ""),
            Word().initWith("At the end of the street", dutch = "Aan het eind van de straat", categoryName = ""),
            Word().initWith("The first on the right", dutch = "De eerste rechts", categoryName = ""),
            Word().initWith("The first on the left", dutch = "De eerste links", categoryName = ""),
            Word().initWith("Straight on", dutch = "Rechtdoor", categoryName = ""),
            Word().initWith("Can we eat?", dutch = "Mogen we iets eten?", categoryName = ""),
            Word().initWith("Can we have breakfast?", dutch = "Mogen we een ontbijt?", categoryName = ""),
            Word().initWith("Is there a table free?", dutch = "Heeft u een tafel vrij?", categoryName = ""),
            Word().initWith("A table for four please", dutch = "Een tafel voor vier alstublieft", categoryName = ""),
            Word().initWith("I'd like to book a table for two", dutch = "Ik wil graag een tafel voor twee reserveren", categoryName = ""),
            Word().initWith("The menu please", dutch = "De kaart alstublieft", categoryName = ""),
            Word().initWith("Have you any vegetarian dishes?", dutch = "Heeft u vegetarische gerechten?", categoryName = ""),
            Word().initWith("I'll have ..", dutch = "Ik wil graag ..", categoryName = ""),
            Word().initWith("That was delicious", dutch = "Het was heerlijk", categoryName = ""),
            Word().initWith("It's delicious!", dutch = "Het is heerlijk!", categoryName = ""),
            Word().initWith("It is delicious, but I'm full!", dutch = "Het is heerlijk, maar ik ben vol!", categoryName = ""),
            Word().initWith("That's enough, thanks", dutch = "Dat is genoeg, bedankt", categoryName = ""),
            Word().initWith("Enjoy your meal!", dutch = "Eet smakelijk!", categoryName = ""),
            Word().initWith("This isn't properly cooked", dutch = "Dit is niet goed gekookt", categoryName = ""),
            Word().initWith("We didn't order this", dutch = "We hebben dit niet besteld", categoryName = ""),
            Word().initWith("We ordered ...", dutch = "We hebben ... besteld", categoryName = ""),
            Word().initWith("Where is the toilet please?", dutch = "Waar is het toilet alstublieft?", categoryName = ""),
            Word().initWith("I need a Doctor", dutch = "Ik heb een doktor nodig", categoryName = ""),
            Word().initWith("I am lost", dutch = "Ik ben verdwaald", categoryName = ""),
            Word().initWith("I need help", dutch = "Ik heb hulp nodig", categoryName = ""),
            Word().initWith("Help!", dutch = "Help!", categoryName = ""),
            Word().initWith("Leave me alone!", dutch = "Laat me met rust!", categoryName = ""),
            Word().initWith("I've lost my passport", dutch = "Ik ben mijn paspoort verloren", categoryName = ""),
            Word().initWith("Call the police!", dutch = "Bel de politie!", categoryName = ""),
            Word().initWith("Call an ambulance!", dutch = "Bel een ambulance!", categoryName = ""),
            Word().initWith("Do you have ..?", dutch = "Heeft u ..?", categoryName = ""),
            Word().initWith("Is there ..?", dutch = "Is er ..?", categoryName = ""),
            Word().initWith("For me", dutch = "Voor mij", categoryName = ""),
            Word().initWith("For him", dutch = "Voor hem", categoryName = ""),
            Word().initWith("For her", dutch = "Voor haar", categoryName = ""),
            Word().initWith("The bill please", dutch = "De rekening alstublieft", categoryName = ""),
            Word().initWith("Keep the change", dutch = "Laat maar zitten", categoryName = ""),
            Word().initWith("It's my round", dutch = "Dit rondje is van mij", categoryName = ""),
            Word().initWith("What would you like to drink?", dutch = "Wat wil je drinken?", categoryName = ""),
            Word().initWith("Cheers!", dutch = "Proost!", categoryName = ""),
            Word().initWith("I'm feeling drunk!", dutch = "Ik ben een beetje dronken", categoryName = ""),
            Word().initWith("I feel ill", dutch = "Ik voel me ziek", categoryName = ""),
            Word().initWith("The wine list please", dutch = "De wijnkaart alstublieft", categoryName = ""),
            Word().initWith("Same again please", dutch = "Hetzelfde nog een keer alstublieft", categoryName = ""),
            Word().initWith("Do you have a map of ..?", dutch = "Heeft u een kaart van ..?", categoryName = ""),
            Word().initWith("How long does it take to get to ..?", dutch = "Hoe lang is het naar ..?", categoryName = ""),
            Word().initWith("Is this seat occupied?", dutch = "Is deze plaats bezet?", categoryName = ""),
            Word().initWith("Do I need to change?", dutch = "Moet ik overstappen?", categoryName = ""),
            Word().initWith("A single ticket", dutch = "Een enkele reis", categoryName = ""),
            Word().initWith("A return ticket", dutch = "Een retourtje", categoryName = ""),
            Word().initWith("Is there a discount for children?", dutch = "Krijgen kinderen korting?", categoryName = ""),
            Word().initWith("Is there a discount for pensioners?", dutch = "Krijgen ouderen korting?", categoryName = ""),
            Word().initWith("A ticket for ..", dutch = "Een kaartje naar ..", categoryName = ""),
            Word().initWith("Is this the train for ..?", dutch = "Gaat deze trein naar ..?", categoryName = ""),
            Word().initWith("When does the train leave?", dutch = "Wanneer vertrekt de trein?", categoryName = ""),
            Word().initWith("What platform does the train leave from?", dutch = "Van welk perron vertrekt de trein?", categoryName = ""),
            Word().initWith("The bus stop", dutch = "De bushalte", categoryName = ""),
            Word().initWith("When is the next bus?", dutch = "Wanneer is de volgende bus?", categoryName = ""),
            Word().initWith("When is the last bus?", dutch = "Wanneer is de laatste bus?", categoryName = ""),
            Word().initWith("What time does it leave?", dutch = "Hoe laat vertrekt hij?", categoryName = ""),
            Word().initWith("When does it arrive?", dutch = "Hoe laat komt hij aan?", categoryName = ""),
            Word().initWith("Is this taxi occupied?", dutch = "Is deze taxi bezet?", categoryName = ""),
            Word().initWith("I want to go to ..", dutch = "Ik wil naar ..", categoryName = ""),
            Word().initWith("How much to go to ..?", dutch = "Hoe veel kost het naar ..?", categoryName = ""),
            Word().initWith("It's near here", dutch = "Het is hier dichtbij", categoryName = ""),
            Word().initWith("Will you slow down", dutch = "Kunt u iets langzamer rijden", categoryName = ""),
            Word().initWith("Stop here", dutch = "Hier stoppen", categoryName = ""),
            Word().initWith("Can you turn the meter on?", dutch = "Kunt u de meter aanzetten?", categoryName = ""),
            Word().initWith("Do you have a road map?", dutch = "Heeft u een wegenkaart?", categoryName = ""),
            Word().initWith("Please fill the tank", dutch = "Volgooien alstublieft", categoryName = ""),
            Word().initWith("Will you check the tyre pressure?", dutch = "Kunt u de bandenspanning controleren?", categoryName = ""),
            Word().initWith("Will you check the headlights?", dutch = "Kunt u de koplampen controleren?", categoryName = ""),
            Word().initWith("My car's broken down", dutch = "Mijn auto is kapot", categoryName = ""),
            Word().initWith("Can you repair it?", dutch = "Kunt u het repareren?", categoryName = ""),
            Word().initWith("I've got a puncture", dutch = "Ik heb een lekke band", categoryName = ""),
            Word().initWith("I've run out of petrol", dutch = "Ik heb geen benzine meer", categoryName = ""),
            Word().initWith("I've had an accident", dutch = "Ik heb een ongeluk gehad", categoryName = ""),
            Word().initWith("Is there a bed and breakfast nearby?", dutch = "Is er een pension in de buurt?", categoryName = ""),
            Word().initWith("Is there a station nearby?", dutch = "Is er een station in de buurt?", categoryName = ""),
            Word().initWith("Is there a campsite nearby?", dutch = "Is er een camping in de buurt?", categoryName = ""),
            Word().initWith("Where can I check my e-mail?", dutch = "Waar kan ik mijn email nakijken?", categoryName = ""),
            Word().initWith("Where can I get internet access?", dutch = "Waar kan ik internetten?", categoryName = ""),
            Word().initWith("Is it safe to swim here?", dutch = "Kun je veilig zwemmen hier?", categoryName = ""),
            Word().initWith("I have a headache", dutch = "Ik heb hoofdpijn", categoryName = ""),
            Word().initWith("I have a sore throat", dutch = "Ik heb een zere keel", categoryName = ""),
            Word().initWith("I feel sick", dutch = "Ik voel me niet lekker", categoryName = ""),
            Word().initWith("I have a cold", dutch = "Ik ben verkouden", categoryName = ""),
            Word().initWith("I have diarrhoea", dutch = "Ik heb diarree", categoryName = ""),
            Word().initWith("I've been stung by a bee", dutch = "Ik ben door een bij gestoken", categoryName = ""),
            Word().initWith("I have sunstroke", dutch = "Ik heb een zonnesteek", categoryName = ""),
            Word().initWith("I have dizzy spells", dutch = "Ik voel me duizelig", categoryName = ""),
            Word().initWith("the bookcase", dutch = "De boekenkast", categoryName = ""),
            Word().initWith("the picture", dutch = "Het schilderij", categoryName = ""),
            Word().initWith("The money", dutch = "Het geld", categoryName = ""),
            Word().initWith("The credit card", dutch = "De creditcard", categoryName = ""),
            Word().initWith("Where can I change money?", dutch = "Waar kan ik geld wisselen?", categoryName = ""),
            Word().initWith("Is there a bank nearby?", dutch = "Is er een bank in de buurt?", categoryName = ""),
            Word().initWith("What is the exchange rate?", dutch = "Wat is de wisselkoers?", categoryName = ""),
            Word().initWith("I'd like to change some pounds", dutch = "Ik wil een paar ponden wisselen", categoryName = ""),
            Word().initWith("I'd like to change some dollars", dutch = "Ik wil een paar dollars wisselen", categoryName = ""),
            Word().initWith("Please give me some small change", dutch = "Kunt u me kleingeld geven alstublieft", categoryName = ""),
            Word().initWith("Please will you give me a receipt", dutch = "Kunt u me een bonnetje geven alstublieft", categoryName = ""),
            Word().initWith("the arm", dutch = "de arm", categoryName = ""),
            Word().initWith("the finger", dutch = "de vinger", categoryName = ""),
            Word().initWith("the face", dutch = "het gezicht", categoryName = ""),
            Word().initWith("the foot", dutch = "de voet", categoryName = ""),
            Word().initWith("the head", dutch = "het hoofd", categoryName = ""),
            Word().initWith("the leg", dutch = "het been", categoryName = ""),
            Word().initWith("the mouth", dutch = "de mond", categoryName = ""),
            Word().initWith("the stomach", dutch = "de maag", categoryName = ""),
            Word().initWith("the thumb", dutch = "de duim", categoryName = ""),
            Word().initWith("the airport", dutch = "De luchthaven", categoryName = ""),
            Word().initWith("the baker's shop", dutch = "De bakkerij", categoryName = ""),
            Word().initWith("the bank", dutch = "De bank", categoryName = ""),
            Word().initWith("the beach", dutch = "Het strand", categoryName = ""),
            Word().initWith("the cafe", dutch = "Het café", categoryName = ""),
            Word().initWith("the campsite", dutch = "De camping", categoryName = ""),
            Word().initWith("the cathedral", dutch = "De kathedraal", categoryName = ""),
            Word().initWith("the chemist's", dutch = "De apotheek", categoryName = ""),
            Word().initWith("the church", dutch = "De kerk", categoryName = ""),
            Word().initWith("the hospital", dutch = "Het ziekenhuis", categoryName = ""),
            Word().initWith("the hotel", dutch = "Het hotel", categoryName = ""),
            Word().initWith("the laundrette", dutch = "De wasserette", categoryName = ""),
            Word().initWith("the market", dutch = "De markt", categoryName = ""),
            Word().initWith("the police station", dutch = "Het politiebureau", categoryName = ""),
            Word().initWith("the post office", dutch = "Het postkantoor", categoryName = ""),
            Word().initWith("the road", dutch = "De weg", categoryName = ""),
            Word().initWith("the street", dutch = "De straat", categoryName = ""),
            Word().initWith("the swimming pool", dutch = "Het zwembad", categoryName = ""),
            Word().initWith("the supermarket", dutch = "De supermarkt", categoryName = ""),
            Word().initWith("the tourist office", dutch = "Het VVV kantoor", categoryName = ""),
            Word().initWith("the town centre", dutch = "Het centrum van de stad", categoryName = ""),
            Word().initWith("Who?", dutch = "Wie?", categoryName = ""),
            Word().initWith("Where?", dutch = "Waar?", categoryName = ""),
            Word().initWith("What?", dutch = "Wat?", categoryName = ""),
            Word().initWith("Why?", dutch = "Waarom?", categoryName = ""),
            Word().initWith("When?", dutch = "Wanneer?", categoryName = ""),
            Word().initWith("How?", dutch = "Hoe?", categoryName = ""),
            Word().initWith("large", dutch = "groot", categoryName = ""),
            Word().initWith("small", dutch = "klein", categoryName = ""),
            Word().initWith("more", dutch = "meer", categoryName = ""),
            Word().initWith("less", dutch = "minder", categoryName = ""),
            Word().initWith("I have booked a room", dutch = "Ik heb een kamer gereserveerd", categoryName = ""),
            Word().initWith("I haven't booked a room", dutch = "Ik heb geen kamer gereserveerd", categoryName = ""),
            Word().initWith("I would like a single room", dutch = "Ik wil een éénpersoonskamer", categoryName = ""),
            Word().initWith("I would like a double room", dutch = "Ik wil een tweepersoonskamer", categoryName = ""),
            Word().initWith("For three nights", dutch = "Voor drie nachten", categoryName = ""),
            Word().initWith("How much is it per night?", dutch = "Hoeveel kost het per nacht?", categoryName = ""),
            Word().initWith("Can I see it?", dutch = "Kan ik even kijken?", categoryName = ""),
            Word().initWith("I like the room", dutch = "Ik vind de kamer mooi", categoryName = ""),
            Word().initWith("I don't like it", dutch = "Ik vind hem niet mooi", categoryName = ""),
            Word().initWith("I'll take it", dutch = "Ik neem hem", categoryName = ""),
            Word().initWith("A room with en suite", dutch = "Een kamer en suite", categoryName = ""),
            Word().initWith("A reservation", dutch = "Een reservering", categoryName = ""),
            Word().initWith("It is too expensive", dutch = "Het is te duur", categoryName = ""),
            Word().initWith("Have you got something cheaper?", dutch = "Heeft u iets goedkopers?", categoryName = ""),
            Word().initWith("Is there air conditioning?", dutch = "Is er airconditioning?", categoryName = ""),
            Word().initWith("The air conditioning is not working", dutch = "De airconditioning doet het niet", categoryName = ""),
            Word().initWith("Will you give me an extra pillow?", dutch = "Kunt u me een extra kussen geven?", categoryName = ""),
            Word().initWith("Can I have some toilet paper?", dutch = "Mag ik wat toiletpapier?", categoryName = ""),
            Word().initWith("Can I pay by credit card?", dutch = "Kan ik met creditcard betalen?", categoryName = ""),
            Word().initWith("Can I pay by traveler's cheque?", dutch = "Kan ik met traveller's cheques betalen?", categoryName = ""),
            Word().initWith("There's a mistake in the bill", dutch = "Er staat een foutje op de rekening", categoryName = ""),
            Word().initWith("We've enjoyed our stay", dutch = "We vonden het leuk hier te zijn", categoryName = ""),
            Word().initWith("the basement", dutch = "de kelder", categoryName = ""),
            Word().initWith("What time is it?", dutch = "Hoe laat is het?", categoryName = ""),
            Word().initWith("Customs", dutch = "Douane", categoryName = ""),
            Word().initWith("Exit", dutch = "Uitgang", categoryName = ""),
            Word().initWith("Entrance", dutch = "Ingang", categoryName = ""),
            Word().initWith("Toilet", dutch = "Toilet", categoryName = ""),
            Word().initWith("Open", dutch = "Open", categoryName = ""),
            Word().initWith("Closed", dutch = "Gesloten", categoryName = ""))
}